# You can replace the contents of this file with your installation's kubeconfig for easy access
# BE CAREFULL HOW YOU DISTRIBUTE THIS DATA. YOU MAY NOT WANT TO VERSION CONTROL THIS FILE
apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: <Change me>
      server: https://<Change me>:6443 # If you are running on a different port also change the port
    name: default
contexts:
  - context:
      cluster: default
      user: default
    name: default
current-context: default
kind: Config
preferences: {}
users:
  - name: default
    user:
      client-certificate-data: <Change me>
      client-key-data: <Change me>
