apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-cluster-issuer
spec:
  acme:
    email: <Change me> # Your email

    # Configure your server here. Try with staging first and then uncomment and push for production
    # Lets encrypt offers 2 servers for issuing so that you don't run into rate limits (5 per issues per day)
    # ---
    # Letsencrypt Production
    # server: https://acme-v02.api.letsencrypt.org/directory
    # - or -
    # Letsencrypt Staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: acme-cluster-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
