apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    name: ""
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.4.0
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
