apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer
spec:
  destination:
    name: ""
    namespace: "cert-manager"
    server: "https://kubernetes.default.svc"
  source:
    path: cluster-issuer
    repoURL: <Change me> # The repo of your GitOps repository hosting the manifests of your apps
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
